#!/bin/sh /etc/rc.common
# MOJA App Web Service
# Copyright (C) 2016 BRCK LTD.

START=75

USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param respawn ${respawn_threshold:=3600} ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_set_param command /usr/bin/gunicorn --workers 4 --bind 127.0.0.1:8050  app:app --chdir /externaldrive/moja-ads
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param user root # run as root
    procd_close_instance
}
